version: '3'
services:
  front:
    build:
      context: .
      dockerfile: ./Dockerfile.front.yml
    ports:
      - "4200:80"

  api:
    build:
      context: .
      dockerfile: ./Dockerfile.api.yml
    ports:
      - "3000:3000"  # TODO : le port 3000 correspond à celui configuré ?

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: sassy
      POSTGRES_PASSWORD: sassiest
      POSTGRES_DB: slayers
    ports:
      - "5434:5432"